fn main() {
    windows::build!(
        Windows::Win32::WindowsAndMessaging::{
            HWND,
            WPARAM,
            LPARAM,
            WM_DESTROY,
            PostQuitMessage,
            DefWindowProcW,
            WNDCLASSW,
            WNDCLASS_STYLES,
            RegisterClassW,
            CreateWindowExW,
            CW_USEDEFAULT,
            ShowWindow,
            SHOW_WINDOW_CMD,
            MSG,
            GetMessageW,
            TranslateMessage,
            DispatchMessageW,
            WINDOW_EX_STYLE,
        },
        Windows::Win32::SystemServices::{
            LRESULT,
            HINSTANCE,
            PWSTR,
            GetModuleHandleW,
        },
        Windows::Win32::MenusAndResources::{
            HICON,
            HCURSOR,
        },
        Windows::Win32::Gdi::HBRUSH,
    );
}
