[package]
authors = ["BeLeap <changseo_jang@korea.ac.kr>"]
edition = "2018"
name = "module_2"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = "0.10.0"

[build-dependencies]
windows = "0.10.0"
